#versions identifiers must not have dots in them in this version catalog file
[versions]
kotlin = "2.3.0"
agp = "8.12.3"
testballoon = "0.8.2-K2.3.0"
signum="3.19.2"
supreme="0.11.2"
uuid="0.8.1"
jsonpath="3.0.0"
jvmJson="20230618"
jvmCbor="1.21"
eupid="3.2.0"
mdl="1.3.0"
obor="2.1.3"
testballoonAddons = "0.7.1"

